### ISSUE TITLE
TypeScript Error, versioning ? Oak

### ISSUE THREAD

**Issue by OverGlass** [tajpouria/cors#1]
Hello ! Thanks for that Middleware. 
I got that TS error.

> error: TS2345 [ERROR]: Argument of type 'import("https://deno.land/x/oak/middleware").Middleware<Record<string, any>, import("https://deno.land/x/oak/context").Context<Record<string, any>>>' is not assignable to parameter of type 'import("https://deno.land/x/oak@v4.0.0/middleware").Middleware<Record<string, any>, import("https://deno.land/x/oak@v4.0.0/context").Context<Record<string, any>>>'.
  Types of parameters 'context' and 'context' are incompatible.
    Type 'import("https://deno.land/x/oak@v4.0.0/context").Context<Record<string, any>>' is not assignable to type 'import("https://deno.land/x/oak/context").Context<Record<string, any>>'.
      Types of property 'app' are incompatible.
        Type 'import("https://deno.land/x/oak@v4.0.0/application").Application<any>' is not assignable to type 'import("https://deno.land/x/oak/application").Application<any>'.
          Property '#middleware' in type 'Application' refers to a different member that cannot be accessed from within type 'Application'.
app.use(oakCors());

I think it's due to versioning. I fixed that by a `@ts-ignore` before `app.use(oakCors());`

**Comment by tajpouria** [comment]
@OverGlass Thank you for reporting this issue, Since they are constantly change middle ware API I just completely get rid of their types definitions, But there is no breaking change in cors.
