### ISSUE TITLE
Trailing characters error while importing oakCors

### ISSUE THREAD

**Issue by tamasszoke** [tajpouria/cors#12]
Hello, I got an issue while importing `oakCors`.

**Code**:

The "Simple Usage" example from the readme, [link](https://github.com/tajpouria/cors#simple-usage-enable-all-cors-requests).

I tried to use it in another deno app too, but the result was the same.

**Command:**

    deno run --allow-read --allow-net corsTest.ts

**Result:**

    error: trailing characters at line 31 column 2
    Imported from "https://deno.land/x/cors/oakCors.ts:2"

It seems the source of the error is the import line:

    import { oakCors } from "https://deno.land/x/cors/mod.ts";

**Deno version:**

    deno 1.1.1
    v8 8.5.104
    typescript 3.9.2

Unfortunately, I couldn't find a solution to this, so any help would be appreciated!

**Comment by tajpouria** [comment]
@tamasszoke Seems like deno/rust issue, Can you try following command?
```sh
deno run --allow-net https://raw.githubusercontent.com/tajpouria/cors/master/examples/oak/simple-usage-enable-all-cors-requests.ts
```

**Comment by tamasszoke** [comment]
@tajpouria Of course, here's the full result:

    Download https://raw.githubusercontent.com/tajpouria/cors/master/examples/oak/simple-usage-enable-all-cors-requests.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/mod.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/types.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/oakCors.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/abcCors.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/mithCors.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/attainCors.ts
    Download https://raw.githubusercontent.com/tajpouria/cors/master/cors.ts
    error: trailing characters at line 31 column 2
    Imported from "https://raw.githubusercontent.com/tajpouria/cors/master/mithCors.ts:2"

**Tested on**:

    Kernel: Linux 4.15.0-88-generic (x86_64)
    Version: #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
    C Library: GNU C Library / (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
    Distribution: Linux Lite 4.8

**Comment by tajpouria** [comment]
@tamasszoke I pretty sure there is nothing wrong with cors module,
I think this is an environment specific problem, Personally recommend Docker, It will be great if you let us know how you solving this problem.

Running same command on Ubuntu 20.04 LTS, deno 1.1.1:
```
deno run --allow-net https://raw.githubusercontent.com/tajpouria/cors/master/examples/oak/simple-usage-enable-all-cors-requests.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/examples/oak/simple-usage-enable-all-cors-requests.ts
Download https://deno.land/x/oak/mod.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/mod.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/types.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/oakCors.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/abcCors.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/mithCors.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/attainCors.ts
Download https://raw.githubusercontent.com/tajpouria/cors/master/cors.ts
Download https://deno.land/x/oak/application.ts
Download https://deno.land/x/oak/context.ts
Download https://deno.land/x/oak/helpers.ts
Download https://deno.land/x/oak/cookies.ts
Download https://deno.land/x/oak/httpError.ts
Download https://deno.land/x/oak/middleware.ts
Download https://deno.land/x/oak/multipart.ts
Download https://deno.land/x/oak/request.ts
Download https://deno.land/x/oak/response.ts
Download https://deno.land/x/oak/router.ts
Download https://deno.land/x/oak/send.ts
Download https://deno.land/x/oak/server_sent_event.ts
Download https://deno.land/x/oak/types.d.ts
Download https://deno.land/x/oak/util.ts
Download https://deno.land/x/oak/deps.ts
Download https://deno.land/x/cors/cors.ts
Download https://deno.land/x/oak/buf_reader.ts
Download https://deno.land/x/oak/content_disposition.ts
Download https://deno.land/x/oak/headers.ts
Download https://deno.land/x/oak/keyStack.ts
Download https://deno.land/x/oak/isMediaType.ts
Download https://deno.land/x/oak/negotiation/charset.ts
Download https://deno.land/x/oak/negotiation/encoding.ts
Download https://deno.land/x/oak/negotiation/language.ts
Download https://deno.land/x/oak/negotiation/mediaType.ts
Download https://deno.land/x/cors/types.ts
Download https://deno.land/std@0.58.0/bytes/mod.ts
Download https://deno.land/std@0.58.0/hash/sha1.ts
Download https://deno.land/std@0.58.0/hash/sha256.ts
Download https://deno.land/std@0.58.0/http/server.ts
Download https://deno.land/std@0.58.0/http/http_status.ts
Download https://deno.land/std@0.58.0/io/bufio.ts
Download https://deno.land/std@0.58.0/io/util.ts
Download https://deno.land/std@0.58.0/path/mod.ts
Download https://deno.land/std@0.58.0/testing/asserts.ts
Download https://deno.land/std@0.58.0/ws/mod.ts
Download https://deno.land/x/media_types@v2.3.7/mod.ts
Download https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts
Download https://deno.land/x/oak/mediaTyper.ts
Download https://deno.land/x/oak/negotiation/common.ts
Download https://deno.land/x/oak/tssCompare.ts
Download https://deno.land/x/media_types@v2.3.7/db.ts
Download https://deno.land/x/media_types@v2.3.7/deps.ts
Download https://deno.land/std@0.58.0/path/_constants.ts
Download https://deno.land/std@0.58.0/path/win32.ts
Download https://deno.land/std@0.58.0/path/posix.ts
Download https://deno.land/std@0.58.0/path/common.ts
Download https://deno.land/std@0.58.0/path/separator.ts
Download https://deno.land/std@0.58.0/path/_interface.ts
Download https://deno.land/std@0.58.0/path/glob.ts
Download https://deno.land/std@0.58.0/encoding/utf8.ts
Download https://deno.land/std@0.58.0/_util/assert.ts
Download https://deno.land/std@0.58.0/async/mod.ts
Download https://deno.land/std@0.58.0/http/_io.ts
Download https://deno.land/std@0.58.0/fmt/colors.ts
Download https://deno.land/std@0.58.0/testing/diff.ts
Download https://deno.land/std@0.58.0/_util/has_own_property.ts
Download https://deno.land/std@0.58.0/io/ioutil.ts
Download https://deno.land/std@0.58.0/textproto/mod.ts
Download https://deno.land/std@0.58.0/async/deferred.ts
Download https://deno.land/std@0.58.0/path/_util.ts
Download https://deno.land/std@0.58.0/path/_globrex.ts
Download https://deno.land/std@0.58.0/async/delay.ts
Download https://deno.land/std@0.58.0/async/mux_async_iterator.ts
Compile https://raw.githubusercontent.com/tajpouria/cors/master/examples/oak/simple-usage-enable-all-cors-requests.ts
CORS-enabled web server listening on port 8000
```

**Comment by tamasszoke** [comment]
I think I figured it out, the raw **oakCors.ts** worked:

    import { oakCors } from "https://raw.githubusercontent.com/tajpouria/cors/master/oakCors.ts"

That led me to the conclusion that the problem is inside the **mod.ts** file, so I tried the **abcCors.ts**, **mithCors.ts**, and the **attainCors.ts** just like I did with the oakCors, it turned out the **mithCors.ts** caused the error.

After looking into it I found the second import is different than the other files.

**mithCors.ts**

    import { Cors } from "https://deno.land/x/cors/cors.ts";

Others:

    import { Cors } from "./cors.ts";

So the import from the url caused my problem, I've made a pull request which change it to relave path as the others.

**Comment by tajpouria** [comment]
@tamasszoke Thank your for PR #13, That's totally make scenes.
