### ISSUE TITLE
Causes Oak to not display response

### ISSUE THREAD

**Issue by mblode** [tajpouria/cors#2]
I'm trying to enable CORS with Deno and Oak for my API. I've added:

`import { oakCors } from 'https://deno.land/x/cors/mod.ts';` and `app.use(oakCors());`

to my index.ts but when I go to the follow console.log in Firefox:

```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

I get the following error in Chrome:

```
HTTP/1.1 404 Not Found
access-control-allow-origin: *
content-length: 0
```

**Comment by tajpouria** [comment]
@mblode Thank you for reporting this issue, We applied fixes on master, There is not breaking change on cors API

**Comment by mblode** [comment]
Thank you so much! Saved me from writing my own CORS middleware! I’m creating a deno, oak, mongodb API
