### ISSUE TITLE
Preflight Option not filtered out

### ISSUE THREAD

**Issue by pwhitdog** [tajpouria/cors#24]
When sending posts the preflight checks are not filtered out. I have to hand write a check in my custom middleware.

**Comment by jsejcksn** [comment]
It seems that whether the `preflightContinue` option is `true` or `false`, the `next()` function is invoked either way:

https://github.com/tajpouria/cors/blob/f66cfb827b30de1ea3b58f7a351ad8d52d1b63d8/cors.ts#L96-L101

@tajpouria Should `next()` be invoked if `preflightContinue` is set to `false` (the default)?

In my case, requests using the `OPTIONS` method must be explicitly terminated. Example:

```ts
gqlRouter.options('/graphql', () => {});
```

@pwhitdog Which framework did you use? I was trying to use [`oak`](https://deno.land/x/oak) with an oak [`graphql`](https://deno.land/x/oak_graphql) middleware.

**Comment by tajpouria** [comment]
@jsejcksn Yeah that is not correct, I should end the request on line no. [100](https://github.com/expressjs/cors/blob/master/lib/index.js#L180).

**Comment by tajpouria** [comment]
Fixed at https://deno.land/x/cors@v1.2.2
