### ISSUE TITLE
Getting Preflight error on post request

### ISSUE THREAD

**Issue by sarthaksavvy** [tajpouria/cors#8]
I am using oakCors and successully added for get request

When I use post request then I am getting 
```js
Access to XMLHttpRequest at 'http://localhost:4000/login' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

I have also used `.options("/login", oakCors())` but not working

**Comment by sarthaksavvy** [comment]
when I use ctx.response.status = 404 for my last route to handle not found, then I get this error.

I removed it and its working find on other routes

**Comment by tajpouria** [comment]
@sarthaksavvy Nice,totally make sense
